#!/bin/bash
sudo echo 'Authorizing sudo for session'
#############
# Variables #
#############
PACKAGES_AUR="oh-my-zsh-git rofi-calc gitflow-avh zsh-theme-powerlevel10k-git"

PACKAGES_UNINSTALL_RECURSIVE="xfce4-terminal"

COC_LANGUAGES="coc-json coc-tsserver coc-markdownlint coc-phpls coc-vetur coc-sql"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

#############
# Execution #
############
# Reload font cache
fc-cache -f -v &> /dev/null

sudo pacman -Su
sudo pacman -S --quiet --clean --noconfirm --needed $(comm -12 <(pacman -Slq | sort) <(sort pkglist.txt))

yay
yay --noconfirm --nocleanmenu --nodiffmenu --noupgrademenu --noremovemake --redownloadall -q -S $PACKAGES_AUR
yay --noconfirm --nocleanmenu --nodiffmenu --noupgrademenu --noremovemake --redownloadall -q -Rc $PACKAGES_UNINSTALL_RECURSIVE

# Install oh my zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Install vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Install plugins
nvim --headless +PlugInstall +qall

# Install CoC language servers
nvim --headless +CocInstall $COC_LANGUAGES +qall

##############
# Copy files #
##############
cp -rf $SCRIPT_DIR/../.config $HOME/
cp -rf $SCRIPT_DIR $HOME/
cp -rf $SCRIPT_DIR/../.zshrc $HOME/
cp -rf $SCRIPT_DIR/../.p10k.zsh $HOME/
cp -rf $SCRIPT_DIR/../.fonts $HOME/
cp -rf $HOME/.oh-my-zsh $HOME/.config/zsh

################
# Set settings #
################
chsh -s `which zsh`
