#!/bin/bash
sudo echo 'Authorizing sudo for session'
#############
# Variables #
#############
COC_LANGUAGES="coc-json coc-tsserver coc-markdownlint coc-phpls coc-vetur coc-sql"

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

#############
# Execution #
############
# Reload font cache
fc-cache -f -v &> /dev/null

sudo pacman -Su
sudo pacman -S --noconfirm --needed $(comm -12 <(pacman -Slq | sort) <(sort $SCRIPT_DIR/pkglist.txt))

yay
yay --noconfirm --nocleanmenu --nodiffmenu --noupgrademenu --noremovemake --redownloadall -S - < $SCRIPT_DIR/aur_pkglist.txt
yay --noconfirm --nocleanmenu --nodiffmenu --noupgrademenu --noremovemake --redownloadall -Rc xfce4-terminal

# Install oh my zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Install vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

# Install plugins
nvim --headless +PlugInstall +qall

# Install CoC language servers
nvim --headless +CocInstall $COC_LANGUAGES +qall

##############
# Copy files #
##############
cp -rf $SCRIPT_DIR/../.config $HOME/
cp -rf $SCRIPT_DIR $HOME/
cp -rf $SCRIPT_DIR/../.zshrc $HOME/
cp -rf $SCRIPT_DIR/../.p10k.zsh $HOME/
cp -rf $SCRIPT_DIR/../.fonts $HOME/
cp -rf $HOME/.oh-my-zsh $HOME/.config/zsh

############################
# Install Oh My Zsh things #
############################
# Powerlevel10k
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $HOME/.config/zsh/custom/themes/powerlevel10k

# Zsh autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions $HOME/.config/zsh/custom/plugins/zsh-autosuggestions

################
# Set settings #
################
chsh -s `which zsh`
